version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: blog_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123 # İstediğiniz bir şifreyi verebilirsiniz
      POSTGRES_DB: blog_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: